### ISSUE TITLE
Uncaught (in promise) Error: Could not find light.exe or candle.exe

### ISSUE THREAD

**Issue by markmorris** [felixrieseberg/electron-wix-msi#25]
Keeping getting this error no matter what.

`Uncaught (in promise) Error: Could not find light.exe or candle.exe`

Wix Toolset is installed. First time using this Toolset am i missing something?

**Comment by markmorris** [comment]
Had to add environment vars to fix. Maybe should mention in readme?

**Comment by J-Cake** [comment]
What vars did you set to what cause I'm getting it too?

**Comment by timmythetiny** [comment]
You must add C:\Program Files (x86)\WiX Toolset {{version}}\bin to your path variable, replacing {{version}} with your Wix version.
