### ISSUE TITLE
Lots of errors CNDL0014 

### ISSUE THREAD

**Issue by jaarandaz** [felixrieseberg/electron-wix-msi#6]
Probably this is because of how electron-forge is managing package process, but when I try to build the installer it fails because this kind of errors.

`error CNDL0014 : The Component/@Id attribute's value, '04100c53dc5f432d07c04be570365740873_bcf33811_39e7_4040_b3b8_be696fb50ded', is not a legal identifier.  Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).  Every identifier must begin with either a letter or an underscore.`

Do you know, by chance, how to solve this? Thanks.

**Comment by dvillarama** [comment]
I'm having the same issue.  Looks like we need to add not allowing ids that start with '.' or a number.

So in:  https://github.com/felixrieseberg/electron-wix-msi/blob/master/src/creator.ts#L437

return id.replace(/[^A-Za-z0-9_\.]|\.|^[0-9]/g, '_');

**Comment by codebude** [comment]
This error still seems to exist... :disappointed: 

@felixrieseberg - do you plan to fix this near future?
@dvillarama - do those IDs have a max lenght? Why not just prefix them with an underscore? (By replacing the first char, you would take some uniqueness, by adding a prefix, the level of uniqueness would stay the same.) --> `return '_'+id.replace(/[^A-Za-z0-9_\.]/g, '_');`

**Comment by moonhead** [comment]
I am seeing the same problem. Has anyone figured out a workaround?

**Comment by KyleMoser** [comment]
Ditto. Using electron forge with Wix. If you file a bug report in the forge repo, they will close it and direct you here....

@felixrieseberg any comment or advice?

**Comment by spidgorny** [comment]
@dvillarama Your suggestions leads to 
```
error LGHT0091 : Duplicate symbol 'Directory:resources_app_node_modules_read_pkg_up_node_modules' found. 
This typically means that an Id is duplicated. 
Check to make sure all your identifiers of a given type (File, Component, Feature) are unique.
```

I have fixed it by using uuid() more agressively with
```
const id = (pathId.length > 20)
```
